gui:
  theme:
    activeBorderColor:
      - "#8992c3"
      - bold
    inactiveBorderColor:
      - "#8f78ba"
    searchingActiveBorderColor:
      - "#b078ba"
      - bold
    optionsTextColor:
      - "#afb0b6"
    selectedLineBgColor:
      - "#262836"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#afb0b6"
    cherryPickedCommitBgColor:
      - "#b078ba"
    markedBaseCommitFgColor:
      - "#b078ba"
    markedBaseCommitBgColor:
      - "#fd4663"
    unstagedChangesColor:
      - "#fd4663"
    defaultFgColor:
      - "#f2f2f3"
