gui:
  theme:
    activeBorderColor:
      - "#7ac3d2"
      - bold
    inactiveBorderColor:
      - "#6b89c7"
    searchingActiveBorderColor:
      - "#7e70c2"
      - bold
    optionsTextColor:
      - "#afb5b6"
    selectedLineBgColor:
      - "#263336"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#afb5b6"
    cherryPickedCommitBgColor:
      - "#7e70c2"
    markedBaseCommitFgColor:
      - "#7e70c2"
    markedBaseCommitBgColor:
      - "#fd4663"
    unstagedChangesColor:
      - "#fd4663"
    defaultFgColor:
      - "#f2f3f3"
