onboarding = false

[keys]
prefix = "ctrl+a"
next_tab = "shift+right"
previous_tab = "shift+left"
split_vertical = "prefix+|"

[ui.toast]
delivery = "system"

[theme.custom]
accent = "#7ac3d2"
panel_bg = "reset"
sidebar_bg = "reset"
active_row_bg = "#263336"
selection_bg = "#2d3f43"
surface0 = "#263336"
surface1 = "#2d3f43"
surface_dim = "#121617"
overlay0 = "#5f6d6f"
overlay1 = "#afb5b6"
text = "#f2f3f3"
subtext0 = "#afb5b6"
mauve = "#a1d3de"
green = "#7ac3d2"
yellow = "#6b89c7"
red = "#fd4663"
blue = "#897ccf"
teal = "#a3b5dc"
peach = "#fd8446"
