onboarding = false

[keys]
prefix = "ctrl+a"
next_tab = "shift+right"
previous_tab = "shift+left"
split_vertical = "prefix+|"

[ui.toast]
delivery = "system"

[theme.custom]
accent = "#8992c3"
panel_bg = "reset"
sidebar_bg = "reset"
active_row_bg = "#262836"
selection_bg = "#2d3043"
surface0 = "#262836"
surface1 = "#2d3043"
surface_dim = "#121217"
overlay0 = "#636673"
overlay1 = "#afb0b6"
text = "#f2f2f3"
subtext0 = "#afb0b6"
mauve = "#aab1d4"
green = "#8992c3"
yellow = "#8f78ba"
red = "#fd4663"
blue = "#b078ba"
teal = "#b9abd4"
peach = "#fd8446"
