onboarding = false

[keys]
prefix = "ctrl+a"
next_tab = "shift+right"
previous_tab = "shift+left"
split_vertical = "prefix+|"

[ui.toast]
delivery = "system"

[theme.custom]
accent = "#c18b8b"
panel_bg = "reset"
sidebar_bg = "reset"
active_row_bg = "#2e2e2e"
selection_bg = "#383838"
surface0 = "#2e2e2e"
surface1 = "#383838"
surface_dim = "#141414"
overlay0 = "#766665"
overlay1 = "#b6afaf"
text = "#f3f2f2"
subtext0 = "#b6afaf"
mauve = "#d3acac"
green = "#c18b8b"
yellow = "#ecf0f4"
red = "#fd4663"
blue = "#ad8585"
teal = "#aebfd0"
peach = "#fd8446"
